services:
  - type: web
    name: foto-verlenger
    runtime: docker
    env: docker
    region: frankfurt
    plan: pro
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeploy: true
    
    disk:
      name: foto-verlenger-disk
      mountPath: /data
      sizeGB: 10
    
    envVars:
      - key: MAX_CONCURRENT_JOBS
        value: "3"
      - key: LOG_LEVEL
        value: info
